on:
  [push, pull_request]:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
          
      - name: Set up env
        run: make setup-linux

      - name: Compile binaries
        run: make

      - name: Run test suite
        run: ./runtests.sh
