on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use OCaml 4.11.1
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1
          
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0.0"
          directory: ${{ runner.temp }}/llvm
          icached: ${{ steps.cache-llvm.outputs.cache-hit }}
          
      - name: Set up env
        run: opam install llvm ocamlfind ocamlbuild

      - name: Compile binaries
        run: |
          eval `opam config env`
          make

      - name: Run AST tests
        run: ./runtests.sh -t ast 

      - name: Run LLVM tests
        run: ./runtests.sh
